openapi: 3.0.1
info:
  title: sample-api
  description: ''
  version: '1.0'
servers:
  - url: https://apiserviceucybmy7vlhi6a.azure-api.net/aaa
paths:
  /sample:
    get:
      summary: サンプルHOGEHOGE
      operationId: sample
      responses:
        '200':
          description: 
  /test-ishikawa:
    get:
      summary: テスト石川
      operationId: test-ishikawa
      responses:
        '200':
          description: 
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]